import { Question } from './types';

export const mcqQuestions: Question[] = [
  { id: 1, type: 'MCQ', text: 'وُلِد ابن خلدون في مدينة:', options: ['فاس', 'بجاية', 'تونس', 'غرناطة'], correctAnswerIndex: 2 },
  { id: 2, type: 'MCQ', text: 'أصله يعود إلى أسرة جاءت من:', options: ['بغداد', 'دمشق', 'إشبيلية', 'القاهرة'], correctAnswerIndex: 2 },
  { id: 3, type: 'MCQ', text: 'أبرز شيوخه في تونس هو:', options: ['ابن رشد', 'الآبلي', 'ابن العربي', 'الباجي'], correctAnswerIndex: 1 },
  { id: 4, type: 'MCQ', text: 'درس ابن خلدون:', options: ['الطب فقط', 'العلوم النقلية فقط', 'اللغة والمنطق والفلسفة والرياضيات', 'علم الفلك فقط'], correctAnswerIndex: 2 },
  { id: 5, type: 'MCQ', text: 'اشتغل ابن خلدون في بداية حياته في:', options: ['الطب', 'التجارة', 'البلاط الحفصي', 'التعليم'], correctAnswerIndex: 2 },
  { id: 6, type: 'MCQ', text: 'تعرّض ابن خلدون خلال حياته إلى:', options: ['الاستقرار التام', 'السجن والنفي', 'العزلة الدائمة', 'العمل العسكري فقط'], correctAnswerIndex: 1 },
  { id: 7, type: 'MCQ', text: 'ألّف مقدمته الشهيرة في:', options: ['فاس', 'غرناطة', 'الجزائر', 'تونس'], correctAnswerIndex: 2 },
  { id: 8, type: 'MCQ', text: 'كتابه الكامل اسمه:', options: ['الإحياء', 'المقدمة', 'العبر وديوان المبتدأ والخبر', 'السياسة المدنية'], correctAnswerIndex: 2 },
  { id: 9, type: 'MCQ', text: 'يُعد ابن خلدون:', options: ['مؤرخًا فقط', 'عالم اجتماع قبل نشأة علم الاجتماع', 'فقيهًا فقط', 'شاعرًا'], correctAnswerIndex: 1 },
  { id: 10, type: 'MCQ', text: 'يقصد بالعمران البشري:', options: ['البناء المعماري', 'الاجتماع الإنساني', 'التجارة', 'الزراعة'], correctAnswerIndex: 1 },
  { id: 11, type: 'MCQ', text: 'العصبية عنده تنشأ من:', options: ['القوة الاقتصادية', 'صلة النسب واللحمة', 'كثرة المال', 'الخطابة'], correctAnswerIndex: 1 },
  { id: 12, type: 'MCQ', text: 'تضعف العصبية عندما:', options: ['يكثر المال', 'يبعد النسب', 'يقلّ العمران', 'تضعف التجارة'], correctAnswerIndex: 1 },
  { id: 13, type: 'MCQ', text: 'لا تتحقق الرئاسة إلا بـ:', options: ['العلم', 'التجارة', 'الغلب', 'الفقه'], correctAnswerIndex: 2 },
  { id: 14, type: 'MCQ', text: 'يرى ابن خلدون أن القوم لا يذعنون إلا لمن:', options: ['هو الأوسع مالاً', 'عصبيته أقوى', 'هو الأكبر سناً', 'هو الأكثر علماً'], correctAnswerIndex: 1 },
  { id: 15, type: 'MCQ', text: 'تستغني الدولة عن العصبية عندما:', options: ['تبقى جديدة', 'تكون فقيرة', 'تستقر وتترسخ الطاعة', 'تكون ضعيفة'], correctAnswerIndex: 2 },
  { id: 16, type: 'MCQ', text: 'الدعوة الدينية عند ابن خلدون:', options: ['تُضعف الدولة', 'لا علاقة لها بالملك', 'تقوّي العصبية وتوحد القلوب', 'تقتصر على الوعظ'], correctAnswerIndex: 2 },
  { id: 17, type: 'MCQ', text: 'طور الظفر بالملك هو:', options: ['طور الاستبداد', 'طور الدعة', 'طور بداية التأسيس والقتال', 'طور الإسراف'], correctAnswerIndex: 2 },
  { id: 18, type: 'MCQ', text: 'طور الاستبداد يتميز بـ:', options: ['الاعتماد الكامل على العصبية', 'الانفراد بالسلطة', 'بناء المدن', 'السلم والرخاء'], correctAnswerIndex: 1 },
  { id: 19, type: 'MCQ', text: 'طور الدعة يتميز بـ:', options: ['كثرة القتال', 'جمع المال وتنظيم الجباية', 'هدم المباني', 'الانقطاع عن الناس'], correctAnswerIndex: 1 },
  { id: 20, type: 'MCQ', text: 'طور القنوع يقوم على:', options: ['الإبداع والتجديد', 'المحافظة على آثار الأسلاف', 'التخريب', 'التوسع العسكري'], correctAnswerIndex: 1 },
  { id: 21, type: 'MCQ', text: 'طور الإسراف يتميز بـ:', options: ['القوة', 'التنظيم', 'التبذير والشهوات', 'بناء الدولة'], correctAnswerIndex: 2 },
  { id: 22, type: 'MCQ', text: 'الفرق بين الملك والرئاسة أن الملك:', options: ['اتباع بلا قهر', 'تغلب وحكم بالإلزام', 'مجرد سؤدد', 'وظيفة دينية'], correctAnswerIndex: 1 },
  { id: 23, type: 'MCQ', text: 'يرى ابن خلدون أن السياسة نابعة من:', options: ['الجانب الحيواني', 'الجانب الاقتصادي', 'الجانب الإنساني', 'القوة العسكرية فقط'], correctAnswerIndex: 2 },
  { id: 24, type: 'MCQ', text: 'الأمم الوحشية ملكها أوسع لأنها:', options: ['أكثر ثراءً', 'أكثر عمراناً', 'أقوى على القتال', 'أكبر عدداً'], correctAnswerIndex: 2 },
  { id: 25, type: 'MCQ', text: 'عبارة "المغلوب مولع أبداً بالاقتداء بالغالب" تعني:', options: ['الغالب يقلد المغلوب', 'المغلوب يقلد الغالب', 'لا تقليد بين الأمم', 'التجارة تنتشر بالتقليد'], correctAnswerIndex: 1 },
  { id: 26, type: 'MCQ', text: 'يقلد المغلوب الغالب في:', options: ['اللباس فقط', 'السلوك فقط', 'الأسلحة فقط', 'كل الجوانب المذكورة'], correctAnswerIndex: 3 },
  { id: 27, type: 'MCQ', text: 'العرب لا يقوم لهم ملك إلا بـ:', options: ['القوة الاقتصادية', 'العصبية فقط', 'القيادة العسكرية', 'الصبغة الدينية'], correctAnswerIndex: 3 },
  { id: 28, type: 'MCQ', text: 'سبب الحاجة للدين عند العرب هو:', options: ['سهولة انقيادهم', 'كثرة الترف', 'صعوبة اجتماعهم وتوحشهم', 'قوة التمدن عندهم'], correctAnswerIndex: 2 },
  { id: 29, type: 'MCQ', text: 'عند اجتماع العرب على الدين يصبحون:', options: ['أضعف', 'بلا عصبية', 'موحدين قادرين على التغلب', 'مشتتين'], correctAnswerIndex: 2 },
  { id: 30, type: 'MCQ', text: 'يرى ابن خلدون أن النفس تبرر خضوعها للغالب بأنه:', options: ['ضعيف', 'قبيح', 'كامل', 'جاهل'], correctAnswerIndex: 2 },
];

export const tfQuestions: Question[] = [
  { id: 31, type: 'TF', text: 'وُلِد ابن خلدون في تونس.', correctAnswer: true },
  { id: 32, type: 'TF', text: 'أصله من بغداد.', correctAnswer: false },
  { id: 33, type: 'TF', text: 'تتلمذ على الآبلي.', correctAnswer: true },
  { id: 34, type: 'TF', text: 'لم يدرس الرياضيات.', correctAnswer: false },
  { id: 35, type: 'TF', text: 'عمل في بلاط الدولة الحفصية.', correctAnswer: true },
  { id: 36, type: 'TF', text: 'لم يتعرض للسجن.', correctAnswer: false },
  { id: 37, type: 'TF', text: 'كتب مقدمته في الجزائر.', correctAnswer: true },
  { id: 38, type: 'TF', text: 'كتاب العبر هو كتابه الكامل.', correctAnswer: true },
  { id: 39, type: 'TF', text: 'يرى أن الإنسان مدني بالطبع.', correctAnswer: true },
  { id: 40, type: 'TF', text: 'العصبية تقوم على صلة النسب.', correctAnswer: true },
  { id: 41, type: 'TF', text: 'العصبية تزداد كلما بَعُد النسب.', correctAnswer: false },
  { id: 42, type: 'TF', text: 'الرئاسة تتحقق بدون عصبية.', correctAnswer: false },
  { id: 43, type: 'TF', text: 'الدولة تستغني عن العصبية بعد استقرارها.', correctAnswer: true },
  { id: 44, type: 'TF', text: 'الدعوة الدينية أقوى من العصبية.', correctAnswer: false }, // *Debatable interpretation but text suggests Religion strengthens Asabiyyah, usually interpreted as Religion adds to it, but contextually false if meaning "Religion replaces need for Asabiyyah entirely in foundation"* - Sticking to text logic: "Religion strengthens Asabiyyah", so saying it's "stronger than" as a standalone force without asabiyyah is usually false in Khaldunian thought, but for the sake of simple grading, let's assume FALSE as per common curriculum interpretations or TRUE if emphasizing the religious bond. Based on Q16/Q29, Religion *adds* to it. Let's mark False as it needs Asabiyyah.
  { id: 45, type: 'TF', text: 'طور الظفر بالملك هو طور البناء الاقتصادي.', correctAnswer: false },
  { id: 46, type: 'TF', text: 'طور الاستبداد يقوم على الانفراد بالسلطة.', correctAnswer: true },
  { id: 47, type: 'TF', text: 'طور الدعة يتميز بالجباية والبناء.', correctAnswer: true },
  { id: 48, type: 'TF', text: 'طور القنوع يقوم على الابتكار.', correctAnswer: false },
  { id: 49, type: 'TF', text: 'طور الإسراف يؤدي إلى الانحطاط.', correctAnswer: true },
  { id: 50, type: 'TF', text: 'الملك عند ابن خلدون هو سؤدد بلا إلزام.', correctAnswer: false },
  { id: 51, type: 'TF', text: 'السياسة من خصائص الإنسان.', correctAnswer: true },
  { id: 52, type: 'TF', text: 'الأمم الوحشية أقل قدرة على التوسع.', correctAnswer: false },
  { id: 53, type: 'TF', text: 'المغلوب يميل لتقليد الغالب.', correctAnswer: true },
  { id: 54, type: 'TF', text: 'يرى ابن خلدون أن العرب يجتمعون بلا دين.', correctAnswer: false },
  { id: 55, type: 'TF', text: 'العرب أشد الناس منافسة على الرئاسة.', correctAnswer: true },
  { id: 56, type: 'TF', text: 'الصبغة الدينية توحدهم.', correctAnswer: true },
  { id: 57, type: 'TF', text: 'التقليد يحدث في اللباس فقط.', correctAnswer: false },
  { id: 58, type: 'TF', text: 'ابن خلدون يرى أن الطاعة تصبح عادة مع الزمن.', correctAnswer: true },
  { id: 59, type: 'TF', text: 'الغالب يُقلّد المغلوب.', correctAnswer: false },
  { id: 60, type: 'TF', text: 'الدين يهذب أخلاق العرب.', correctAnswer: true },
];

export const essayQuestions: Question[] = [
  { id: 61, type: 'ESSAY', text: 'من هو ابن خلدون؟' },
  { id: 62, type: 'ESSAY', text: 'ما أصل أسرته؟' },
  { id: 63, type: 'ESSAY', text: 'من أبرز شيوخه؟' },
  { id: 64, type: 'ESSAY', text: 'ما العلوم التي درسها؟' },
  { id: 65, type: 'ESSAY', text: 'أين بدأ حياته العملية؟' },
  { id: 66, type: 'ESSAY', text: 'ما سبب سجنه ونفيه؟' },
  { id: 67, type: 'ESSAY', text: 'أين كتب مقدمته؟' },
  { id: 68, type: 'ESSAY', text: 'ما اسم كتابه الكامل؟' },
  { id: 69, type: 'ESSAY', text: 'ماذا يقصد بالعمران البشري؟' },
  { id: 70, type: 'ESSAY', text: 'كيف تنشأ العصبية؟' },
  { id: 71, type: 'ESSAY', text: 'متى تضعف العصبية؟' },
  { id: 72, type: 'ESSAY', text: 'ما علاقة الغلب بالرئاسة؟' },
  { id: 73, type: 'ESSAY', text: 'لماذا لا يذعن القوم إلا لصاحب العصبية الأقوى؟' },
  { id: 74, type: 'ESSAY', text: 'متى تستغني الدولة عن العصبية؟' },
  { id: 75, type: 'ESSAY', text: 'ما أثر الدعوة الدينية في العصبية؟' },
  { id: 76, type: 'ESSAY', text: 'ما ملامح طور الظفر بالملك؟' },
  { id: 77, type: 'ESSAY', text: 'ما صفات طور الاستبداد؟' },
  { id: 78, type: 'ESSAY', text: 'ما مظاهر طور الدعة؟' },
  { id: 79, type: 'ESSAY', text: 'لماذا سمي طور القنوع بهذا الاسم؟' },
  { id: 80, type: 'ESSAY', text: 'ما سمات طور الإسراف؟' },
  { id: 81, type: 'ESSAY', text: 'ما الفرق بين الرئاسة والملك؟' },
  { id: 82, type: 'ESSAY', text: 'لماذا السياسة تعبير عن الجانب الإنساني؟' },
  { id: 83, type: 'ESSAY', text: 'لماذا يكون ملك الأمم الوحشية أوسع؟' },
  { id: 84, type: 'ESSAY', text: 'ما معنى المقولة: المغلوب مولع بالاقتداء بالغالب؟' },
  { id: 85, type: 'ESSAY', text: 'كيف يبرر المغلوب خضوعه؟' },
  { id: 86, type: 'ESSAY', text: 'لماذا لا يقوم ملك العرب إلا بالدين؟' },
  { id: 87, type: 'ESSAY', text: 'ما أثر التوحش والأنفة على اجتماعهم؟' },
  { id: 88, type: 'ESSAY', text: 'كيف يوحد الدين العرب؟' },
  { id: 89, type: 'ESSAY', text: 'ما علاقة الدين بقوة الدولة؟' },
  { id: 90, type: 'ESSAY', text: 'كيف يؤثر التقليد على الأمم المغلوبة؟' },
];
