import { Exam } from './types';

export const exams: Exam[] = [
  {
    id: 'ibn-khaldun',
    title: 'اختبار ابن خلدون الشامل',
    description: 'اختبر معلوماتك حول مؤسس علم الاجتماع ومقدمته الشهيرة ونظرياته في العمران والعصبية.',
    icon: 'scroll',
    mcqQuestions: [
      { id: 1, type: 'MCQ', text: 'وُلِد ابن خلدون في مدينة:', options: ['فاس', 'بجاية', 'تونس', 'غرناطة'], correctAnswerIndex: 2 },
      { id: 2, type: 'MCQ', text: 'أصله يعود إلى أسرة جاءت من:', options: ['بغداد', 'دمشق', 'إشبيلية', 'القاهرة'], correctAnswerIndex: 2 },
      { id: 3, type: 'MCQ', text: 'أبرز شيوخه في تونس هو:', options: ['ابن رشد', 'الآبلي', 'ابن العربي', 'الباجي'], correctAnswerIndex: 1 },
      { id: 4, type: 'MCQ', text: 'درس ابن خلدون:', options: ['الطب فقط', 'العلوم النقلية فقط', 'اللغة والمنطق والفلسفة والرياضيات', 'علم الفلك فقط'], correctAnswerIndex: 2 },
      { id: 5, type: 'MCQ', text: 'اشتغل ابن خلدون في بداية حياته في:', options: ['الطب', 'التجارة', 'البلاط الحفصي', 'التعليم'], correctAnswerIndex: 2 },
      { id: 6, type: 'MCQ', text: 'تعرّض ابن خلدون خلال حياته إلى:', options: ['الاستقرار التام', 'السجن والنفي', 'العزلة الدائمة', 'العمل العسكري فقط'], correctAnswerIndex: 1 },
      { id: 7, type: 'MCQ', text: 'ألّف مقدمته الشهيرة في:', options: ['فاس', 'غرناطة', 'الجزائر', 'تونس'], correctAnswerIndex: 2 },
      { id: 8, type: 'MCQ', text: 'كتابه الكامل اسمه:', options: ['الإحياء', 'المقدمة', 'العبر وديوان المبتدأ والخبر', 'السياسة المدنية'], correctAnswerIndex: 2 },
      { id: 9, type: 'MCQ', text: 'يُعد ابن خلدون:', options: ['مؤرخًا فقط', 'عالم اجتماع قبل نشأة علم الاجتماع', 'فقيهًا فقط', 'شاعرًا'], correctAnswerIndex: 1 },
      { id: 10, type: 'MCQ', text: 'يقصد بالعمران البشري:', options: ['البناء المعماري', 'الاجتماع الإنساني', 'التجارة', 'الزراعة'], correctAnswerIndex: 1 },
      { id: 11, type: 'MCQ', text: 'العصبية عنده تنشأ من:', options: ['القوة الاقتصادية', 'صلة النسب واللحمة', 'كثرة المال', 'الخطابة'], correctAnswerIndex: 1 },
      { id: 12, type: 'MCQ', text: 'تضعف العصبية عندما:', options: ['يكثر المال', 'يبعد النسب', 'يقلّ العمران', 'تضعف التجارة'], correctAnswerIndex: 1 },
      { id: 13, type: 'MCQ', text: 'لا تتحقق الرئاسة إلا بـ:', options: ['العلم', 'التجارة', 'الغلب', 'الفقه'], correctAnswerIndex: 2 },
      { id: 14, type: 'MCQ', text: 'يرى ابن خلدون أن القوم لا يذعنون إلا لمن:', options: ['هو الأوسع مالاً', 'عصبيته أقوى', 'هو الأكبر سناً', 'هو الأكثر علماً'], correctAnswerIndex: 1 },
      { id: 15, type: 'MCQ', text: 'تستغني الدولة عن العصبية عندما:', options: ['تبقى جديدة', 'تكون فقيرة', 'تستقر وتترسخ الطاعة', 'تكون ضعيفة'], correctAnswerIndex: 2 },
      { id: 16, type: 'MCQ', text: 'الدعوة الدينية عند ابن خلدون:', options: ['تُضعف الدولة', 'لا علاقة لها بالملك', 'تقوّي العصبية وتوحد القلوب', 'تقتصر على الوعظ'], correctAnswerIndex: 2 },
      { id: 17, type: 'MCQ', text: 'طور الظفر بالملك هو:', options: ['طور الاستبداد', 'طور الدعة', 'طور بداية التأسيس والقتال', 'طور الإسراف'], correctAnswerIndex: 2 },
      { id: 18, type: 'MCQ', text: 'طور الاستبداد يتميز بـ:', options: ['الاعتماد الكامل على العصبية', 'الانفراد بالسلطة', 'بناء المدن', 'السلم والرخاء'], correctAnswerIndex: 1 },
      { id: 19, type: 'MCQ', text: 'طور الدعة يتميز بـ:', options: ['كثرة القتال', 'جمع المال وتنظيم الجباية', 'هدم المباني', 'الانقطاع عن الناس'], correctAnswerIndex: 1 },
      { id: 20, type: 'MCQ', text: 'طور القنوع يقوم على:', options: ['الإبداع والتجديد', 'المحافظة على آثار الأسلاف', 'التخريب', 'التوسع العسكري'], correctAnswerIndex: 1 },
      { id: 21, type: 'MCQ', text: 'طور الإسراف يتميز بـ:', options: ['القوة', 'التنظيم', 'التبذير والشهوات', 'بناء الدولة'], correctAnswerIndex: 2 },
      { id: 22, type: 'MCQ', text: 'الفرق بين الملك والرئاسة أن الملك:', options: ['اتباع بلا قهر', 'تغلب وحكم بالإلزام', 'مجرد سؤدد', 'وظيفة دينية'], correctAnswerIndex: 1 },
      { id: 23, type: 'MCQ', text: 'يرى ابن خلدون أن السياسة نابعة من:', options: ['الجانب الحيواني', 'الجانب الاقتصادي', 'الجانب الإنساني', 'القوة العسكرية فقط'], correctAnswerIndex: 2 },
      { id: 24, type: 'MCQ', text: 'الأمم الوحشية ملكها أوسع لأنها:', options: ['أكثر ثراءً', 'أكثر عمراناً', 'أقوى على القتال', 'أكبر عدداً'], correctAnswerIndex: 2 },
      { id: 25, type: 'MCQ', text: 'عبارة "المغلوب مولع أبداً بالاقتداء بالغالب" تعني:', options: ['الغالب يقلد المغلوب', 'المغلوب يقلد الغالب', 'لا تقليد بين الأمم', 'التجارة تنتشر بالتقليد'], correctAnswerIndex: 1 },
      { id: 26, type: 'MCQ', text: 'يقلد المغلوب الغالب في:', options: ['اللباس فقط', 'السلوك فقط', 'الأسلحة فقط', 'كل الجوانب المذكورة'], correctAnswerIndex: 3 },
      { id: 27, type: 'MCQ', text: 'العرب لا يقوم لهم ملك إلا بـ:', options: ['القوة الاقتصادية', 'العصبية فقط', 'القيادة العسكرية', 'الصبغة الدينية'], correctAnswerIndex: 3 },
      { id: 28, type: 'MCQ', text: 'سبب الحاجة للدين عند العرب هو:', options: ['سهولة انقيادهم', 'كثرة الترف', 'صعوبة اجتماعهم وتوحشهم', 'قوة التمدن عندهم'], correctAnswerIndex: 2 },
      { id: 29, type: 'MCQ', text: 'عند اجتماع العرب على الدين يصبحون:', options: ['أضعف', 'بلا عصبية', 'موحدين قادرين على التغلب', 'مشتتين'], correctAnswerIndex: 2 },
      { id: 30, type: 'MCQ', text: 'يرى ابن خلدون أن النفس تبرر خضوعها للغالب بأنه:', options: ['ضعيف', 'قبيح', 'كامل', 'جاهل'], correctAnswerIndex: 2 },
    ],
    tfQuestions: [
      { id: 31, type: 'TF', text: 'وُلِد ابن خلدون في تونس.', correctAnswer: true },
      { id: 32, type: 'TF', text: 'أصله من بغداد.', correctAnswer: false },
      { id: 33, type: 'TF', text: 'تتلمذ على الآبلي.', correctAnswer: true },
      { id: 34, type: 'TF', text: 'لم يدرس الرياضيات.', correctAnswer: false },
      { id: 35, type: 'TF', text: 'عمل في بلاط الدولة الحفصية.', correctAnswer: true },
      { id: 36, type: 'TF', text: 'لم يتعرض للسجن.', correctAnswer: false },
      { id: 37, type: 'TF', text: 'كتب مقدمته في الجزائر.', correctAnswer: true },
      { id: 38, type: 'TF', text: 'كتاب العبر هو كتابه الكامل.', correctAnswer: true },
      { id: 39, type: 'TF', text: 'يرى أن الإنسان مدني بالطبع.', correctAnswer: true },
      { id: 40, type: 'TF', text: 'العصبية تقوم على صلة النسب.', correctAnswer: true },
      { id: 41, type: 'TF', text: 'العصبية تزداد كلما بَعُد النسب.', correctAnswer: false },
      { id: 42, type: 'TF', text: 'الرئاسة تتحقق بدون عصبية.', correctAnswer: false },
      { id: 43, type: 'TF', text: 'الدولة تستغني عن العصبية بعد استقرارها.', correctAnswer: true },
      { id: 44, type: 'TF', text: 'الدعوة الدينية أقوى من العصبية.', correctAnswer: false },
      { id: 45, type: 'TF', text: 'طور الظفر بالملك هو طور البناء الاقتصادي.', correctAnswer: false },
      { id: 46, type: 'TF', text: 'طور الاستبداد يقوم على الانفراد بالسلطة.', correctAnswer: true },
      { id: 47, type: 'TF', text: 'طور الدعة يتميز بالجباية والبناء.', correctAnswer: true },
      { id: 48, type: 'TF', text: 'طور القنوع يقوم على الابتكار.', correctAnswer: false },
      { id: 49, type: 'TF', text: 'طور الإسراف يؤدي إلى الانحطاط.', correctAnswer: true },
      { id: 50, type: 'TF', text: 'الملك عند ابن خلدون هو سؤدد بلا إلزام.', correctAnswer: false },
      { id: 51, type: 'TF', text: 'السياسة من خصائص الإنسان.', correctAnswer: true },
      { id: 52, type: 'TF', text: 'الأمم الوحشية أقل قدرة على التوسع.', correctAnswer: false },
      { id: 53, type: 'TF', text: 'المغلوب يميل لتقليد الغالب.', correctAnswer: true },
      { id: 54, type: 'TF', text: 'يرى ابن خلدون أن العرب يجتمعون بلا دين.', correctAnswer: false },
      { id: 55, type: 'TF', text: 'العرب أشد الناس منافسة على الرئاسة.', correctAnswer: true },
      { id: 56, type: 'TF', text: 'الصبغة الدينية توحدهم.', correctAnswer: true },
      { id: 57, type: 'TF', text: 'التقليد يحدث في اللباس فقط.', correctAnswer: false },
      { id: 58, type: 'TF', text: 'ابن خلدون يرى أن الطاعة تصبح عادة مع الزمن.', correctAnswer: true },
      { id: 59, type: 'TF', text: 'الغالب يُقلّد المغلوب.', correctAnswer: false },
      { id: 60, type: 'TF', text: 'الدين يهذب أخلاق العرب.', correctAnswer: true },
    ],
    essayQuestions: [
      { id: 61, type: 'ESSAY', text: 'من هو ابن خلدون؟' },
      { id: 62, type: 'ESSAY', text: 'ما أصل أسرته؟' },
      { id: 63, type: 'ESSAY', text: 'من أبرز شيوخه؟' },
      { id: 64, type: 'ESSAY', text: 'ما العلوم التي درسها؟' },
      { id: 65, type: 'ESSAY', text: 'أين بدأ حياته العملية؟' },
      { id: 66, type: 'ESSAY', text: 'ما سبب سجنه ونفيه؟' },
      { id: 67, type: 'ESSAY', text: 'أين كتب مقدمته؟' },
      { id: 68, type: 'ESSAY', text: 'ما اسم كتابه الكامل؟' },
      { id: 69, type: 'ESSAY', text: 'ماذا يقصد بالعمران البشري؟' },
      { id: 70, type: 'ESSAY', text: 'كيف تنشأ العصبية؟' },
      { id: 71, type: 'ESSAY', text: 'متى تضعف العصبية؟' },
      { id: 72, type: 'ESSAY', text: 'ما علاقة الغلب بالرئاسة؟' },
      { id: 73, type: 'ESSAY', text: 'لماذا لا يذعن القوم إلا لصاحب العصبية الأقوى؟' },
      { id: 74, type: 'ESSAY', text: 'متى تستغني الدولة عن العصبية؟' },
      { id: 75, type: 'ESSAY', text: 'ما أثر الدعوة الدينية في العصبية؟' },
      { id: 76, type: 'ESSAY', text: 'ما ملامح طور الظفر بالملك؟' },
      { id: 77, type: 'ESSAY', text: 'ما صفات طور الاستبداد؟' },
      { id: 78, type: 'ESSAY', text: 'ما مظاهر طور الدعة؟' },
      { id: 79, type: 'ESSAY', text: 'لماذا سمي طور القنوع بهذا الاسم؟' },
      { id: 80, type: 'ESSAY', text: 'ما سمات طور الإسراف؟' },
      { id: 81, type: 'ESSAY', text: 'ما الفرق بين الرئاسة والملك؟' },
      { id: 82, type: 'ESSAY', text: 'لماذا السياسة تعبير عن الجانب الإنساني؟' },
      { id: 83, type: 'ESSAY', text: 'لماذا يكون ملك الأمم الوحشية أوسع؟' },
      { id: 84, type: 'ESSAY', text: 'ما معنى المقولة: المغلوب مولع بالاقتداء بالغالب؟' },
      { id: 85, type: 'ESSAY', text: 'كيف يبرر المغلوب خضوعه؟' },
      { id: 86, type: 'ESSAY', text: 'لماذا لا يقوم ملك العرب إلا بالدين؟' },
      { id: 87, type: 'ESSAY', text: 'ما أثر التوحش والأنفة على اجتماعهم؟' },
      { id: 88, type: 'ESSAY', text: 'كيف يوحد الدين العرب؟' },
      { id: 89, type: 'ESSAY', text: 'ما علاقة الدين بقوة الدولة؟' },
      { id: 90, type: 'ESSAY', text: 'كيف يؤثر التقليد على الأمم المغلوبة؟' },
    ]
  },
  {
    id: 'al-mawardi',
    title: 'اختبار الماوردي (الأحكام السلطانية)',
    description: 'اختبار يركز على الفكر السياسي للماوردي، كتابه الأحكام السلطانية، ونظريته في الإمامة والوزارة.',
    icon: 'scale',
    mcqQuestions: [
      { id: 1, type: 'MCQ', text: 'وُلِد الماوردي في مدينة:', options: ['بغداد', 'دمشق', 'البصرة', 'نيسابور'], correctAnswerIndex: 2 },
      { id: 2, type: 'MCQ', text: 'سنة ولادة الماوردي هي:', options: ['300هـ', '364هـ', '447هـ', '500هـ'], correctAnswerIndex: 1 },
      { id: 3, type: 'MCQ', text: 'سبب تلقيب الماوردي بهذا الاسم:', options: ['مهنة والده في تجارة ماء الورد', 'كثرة شربه ماء الورد', 'نسبة لمدينة مائية', 'لقب سياسي'], correctAnswerIndex: 0 },
      { id: 4, type: 'MCQ', text: 'نشأة الماوردي العلمية كانت في:', options: ['بيئة تجارية', 'بيئة علمية غنية', 'بيئة ريفية', 'بيئة صناعية'], correctAnswerIndex: 1 },
      { id: 5, type: 'MCQ', text: 'عمل الماوردي في بغداد كـ:', options: ['وزير', 'قائد جيش', 'قاضي القضاة', 'والي الأهواز'], correctAnswerIndex: 2 },
      { id: 6, type: 'MCQ', text: 'من المناصب التي تقلدها:', options: ['خطيب المسجد الأموي', 'قاضي الأهواز', 'قائد الشرطة', 'وزير المال'], correctAnswerIndex: 1 },
      { id: 7, type: 'MCQ', text: 'كانت مهمة الماوردي السياسية تشمل:', options: ['قيادة الجيوش', 'محاربة الفقهاء', 'الوساطة والتفاوض', 'التجارة'], correctAnswerIndex: 2 },
      { id: 8, type: 'MCQ', text: 'القرن الخامس الهجري شهد:', options: ['قوة الخلافة', 'ضعف الخلافة العباسية', 'سيطرة العلماء', 'غياب البويهيين'], correctAnswerIndex: 1 },
      { id: 9, type: 'MCQ', text: 'كتاب "الأحكام السلطانية" يتناول:', options: ['الطب', 'نظام الحكم الإسلامي', 'الشعر العربي', 'تفسير القرآن'], correctAnswerIndex: 1 },
      { id: 10, type: 'MCQ', text: 'يعد كتاب "أدب الدنيا والدين" كتاباً:', options: ['طبياً', 'اقتصادياً', 'أخلاقياً واجتماعياً وسياسياً', 'تاريخياً بحتاً'], correctAnswerIndex: 2 },
      { id: 11, type: 'MCQ', text: 'يرى الماوردي أن الإمامة:', options: ['نظام اجتماعي فقط', 'خلافة للنبوة في حفظ الدين وسياسة الدنيا', 'شأن اختياري لا علاقة له بالدين', 'عمل تطوعي'], correctAnswerIndex: 1 },
      { id: 12, type: 'MCQ', text: 'الإمامة عنده هي:', options: ['فرض عين', 'فرض كفاية', 'سنة مؤكدة', 'مباحة'], correctAnswerIndex: 1 },
      { id: 13, type: 'MCQ', text: 'أهل الاختيار وظيفتهم:', options: ['جباية الأموال', 'حماية الثغور', 'اختيار الإمام', 'القضاء'], correctAnswerIndex: 2 },
      { id: 14, type: 'MCQ', text: 'من شروط أهل الاختيار:', options: ['الشجاعة', 'العدالة والعلم والحكمة', 'الثراء', 'النسب القرشي'], correctAnswerIndex: 1 },
      { id: 15, type: 'MCQ', text: 'عدد شروط الإمامة عند الماوردي:', options: ['ثلاثة', 'خمسة', 'سبعة', 'عشرة'], correctAnswerIndex: 2 },
      { id: 16, type: 'MCQ', text: 'من شروط الإمام:', options: ['الصناعة', 'سلامة الحواس', 'التجارة', 'كثرة الأولاد'], correctAnswerIndex: 1 },
      { id: 17, type: 'MCQ', text: 'من طرق انعقاد الإمامة:', options: ['الوراثة فقط', 'الغلبة', 'اختيار أهل الحل والعقد', 'التوريث الإجباري'], correctAnswerIndex: 2 },
      { id: 18, type: 'MCQ', text: 'إذا رفض المرشح الإمامة:', options: ['يُجبر عليها', 'يُقتل', 'لا يُجبر لأنها عقد رضائي', 'يمنع من الولاية نهائياً'], correctAnswerIndex: 2 },
      { id: 19, type: 'MCQ', text: 'إذا تساوى مرشحان:', options: ['يقدم الأجمل', 'يقدم الأكبر سناً', 'يقدم الأغنى', 'يقدم الأكثر شهرة'], correctAnswerIndex: 1 },
      { id: 20, type: 'MCQ', text: 'إذا احتاج الناس العلم:', options: ['يقدم الأعلم', 'يقدم الأشجع', 'يقدم الأكبر', 'يقدم الأصغر'], correctAnswerIndex: 0 },
      { id: 21, type: 'MCQ', text: 'وظيفة الإمام الأولى هي:', options: ['جمع الضرائب', 'حفظ الدين على أصوله', 'التدريب العسكري', 'القضاء فقط'], correctAnswerIndex: 1 },
      { id: 22, type: 'MCQ', text: 'من وظائف الإمام:', options: ['تعطيل الحدود', 'إقامة الحدود', 'منع الجهاد', 'ترك بيت المال بلا تقدير'], correctAnswerIndex: 1 },
      { id: 23, type: 'MCQ', text: 'من وظائفه أيضاً:', options: ['إضعاف الثغور', 'تحصين الثغور', 'استبدال الجيوش بمرتزقة', 'ترك الحرمين'], correctAnswerIndex: 1 },
      { id: 24, type: 'MCQ', text: 'من وظائف الإمام المالية:', options: ['تكديس المال', 'التقتير فقط', 'تقدير العطايا وصرف بيت المال باعتدال', 'منع الصدقات'], correctAnswerIndex: 2 },
      { id: 25, type: 'MCQ', text: 'يشترط في القاضي:', options: ['الذكورية والحرية والعدالة', 'الثراء', 'أن يكون تجارياً', 'أن يكون محارباً'], correctAnswerIndex: 0 },
      { id: 26, type: 'MCQ', text: 'من أصول الأحكام:', options: ['العقل فقط', 'كتاب الله وسنة الرسول', 'العرف', 'السياسة فقط'], correctAnswerIndex: 1 },
      { id: 27, type: 'MCQ', text: 'يشترط في ناظر المظالم أن يكون:', options: ['كثير الطمع', 'ضعيف الهيبة', 'عظيم الهيبة', 'قليل الفهم'], correctAnswerIndex: 2 },
      { id: 28, type: 'MCQ', text: 'من أعمال ولاية المظالم:', options: ['جمع الشعر', 'مراقبة كتاب الدواوين', 'تعليم الأطفال', 'كتابة الفتاوى فقط'], correctAnswerIndex: 1 },
      { id: 29, type: 'MCQ', text: 'ردّ الغصوب يشمل:', options: ['غصوب سلطانية وأصحاب القوة', 'التجارة', 'المعادن', 'الأراضي الزراعية فقط'], correctAnswerIndex: 0 },
      { id: 30, type: 'MCQ', text: 'وزارة التفويض عند الماوردي تشترط:', options: ['الجهل', 'القوة البدنية', 'شروط الإمامة عدا النسب', 'أن يكون الوزير صغيراً'], correctAnswerIndex: 2 },
    ],
    tfQuestions: [
      { id: 31, type: 'TF', text: 'وُلِد الماوردي في البصرة.', correctAnswer: true },
      { id: 32, type: 'TF', text: 'لقب الماوردي بسبب بيع والده ماء الورد.', correctAnswer: true },
      { id: 33, type: 'TF', text: 'نشأته كانت في بيئة فقيرة بلا علم.', correctAnswer: false },
      { id: 34, type: 'TF', text: 'تقلّد منصب قاضي القضاة في بغداد.', correctAnswer: true },
      { id: 35, type: 'TF', text: 'لم يعمل الماوردي في السياسة.', correctAnswer: false },
      { id: 36, type: 'TF', text: 'القرن الخامس شهد قوة الخلافة.', correctAnswer: false },
      { id: 37, type: 'TF', text: 'كتاب الأحكام السلطانية يعالج نظام الحكم الإسلامي.', correctAnswer: true },
      { id: 38, type: 'TF', text: 'الإمامة عنده فرض كفاية.', correctAnswer: true },
      { id: 39, type: 'TF', text: 'أهل الاختيار هم الذين يتولون الإمامة.', correctAnswer: false },
      { id: 40, type: 'TF', text: 'يشترط في الإمام العدالة والعلم والشجاعة.', correctAnswer: true },
      { id: 41, type: 'TF', text: 'الإمامة تنعقد بالقوة فقط.', correctAnswer: false },
      { id: 42, type: 'TF', text: 'لا يجوز إجبار المرشح على الإمامة.', correctAnswer: true },
      { id: 43, type: 'TF', text: 'يقدم الأعلم في زمن انتشار البدع.', correctAnswer: true },
      { id: 44, type: 'TF', text: 'من وظائف الإمام حماية البيضة.', correctAnswer: true },
      { id: 45, type: 'TF', text: 'إقامة الحدود من وظائفه.', correctAnswer: true },
      { id: 46, type: 'TF', text: 'يجوز له تعطيل الجهاد دائماً.', correctAnswer: false },
      { id: 47, type: 'TF', text: 'لا تُشترط سلامة البصر للقاضي.', correctAnswer: false },
      { id: 48, type: 'TF', text: 'العلم بالأحكام شرط في القضاء.', correctAnswer: true },
      { id: 49, type: 'TF', text: 'أصول الأحكام أربعة.', correctAnswer: true },
      { id: 50, type: 'TF', text: 'ناظر المظالم يجب أن يكون قليل الطمع.', correctAnswer: true },
      { id: 51, type: 'TF', text: 'النظر في تعدي الوالة جزء من عمل المظالم.', correctAnswer: true },
      { id: 52, type: 'TF', text: 'مراقبة الدواوين ليست من أعماله.', correctAnswer: false },
      { id: 53, type: 'TF', text: 'غصوب أصحاب القوة تُرد بالقوة المعنوية.', correctAnswer: true },
      { id: 54, type: 'TF', text: 'وزارة التفويض كوزارة الإمام.', correctAnswer: true },
      { id: 55, type: 'TF', text: 'وزارة التنفيذ تعتمد على اجتهاد الوزير.', correctAnswer: false },
      { id: 56, type: 'TF', text: 'الماوردي يرى ضرورة شرعية لاستمرار الخلافة.', correctAnswer: true },
      { id: 57, type: 'TF', text: 'وظيفة الإمام تشمل تنفيذ الأحكام.', correctAnswer: true },
      { id: 58, type: 'TF', text: 'الإمام لا يُشرف على شؤون الدولة مباشرة.', correctAnswer: false },
      { id: 59, type: 'TF', text: 'يشترط في ناظر المظالم عظم الهيبة.', correctAnswer: true },
      { id: 60, type: 'TF', text: 'الوزارة نوع واحد فقط.', correctAnswer: false },
    ],
    essayQuestions: [
      { id: 61, type: 'ESSAY', text: 'من هو الماوردي؟' },
      { id: 62, type: 'ESSAY', text: 'ما سبب تلقيبه بالماوردي؟' },
      { id: 63, type: 'ESSAY', text: 'أين نشأ وما العلوم التي تعلمها؟' },
      { id: 64, type: 'ESSAY', text: 'ما أبرز مناصبه؟' },
      { id: 65, type: 'ESSAY', text: 'ما دوره السياسي؟' },
      { id: 66, type: 'ESSAY', text: 'ماذا كان وضع الخلافة العباسية في زمنه؟' },
      { id: 67, type: 'ESSAY', text: 'ما أشهر كتبه؟' },
      { id: 68, type: 'ESSAY', text: 'ما موضوع كتاب الأحكام السلطانية؟' },
      { id: 69, type: 'ESSAY', text: 'ما تعريف الإمامة عنده؟' },
      { id: 70, type: 'ESSAY', text: 'ما حكم الإمامة؟' },
      { id: 71, type: 'ESSAY', text: 'من هم أهل الاختيار؟' },
      { id: 72, type: 'ESSAY', text: 'ما شروطهم؟' },
      { id: 73, type: 'ESSAY', text: 'كم عدد شروط الإمامة؟' },
      { id: 74, type: 'ESSAY', text: 'ما شروط الإمام؟' },
      { id: 75, type: 'ESSAY', text: 'كيف تنعقد الإمامة؟' },
      { id: 76, type: 'ESSAY', text: 'ماذا يحدث إذا رفض المرشح؟' },
      { id: 77, type: 'ESSAY', text: 'كيف يختار بين مرشحين متساويين؟' },
      { id: 78, type: 'ESSAY', text: 'ما وظائف الإمام؟' },
      { id: 79, type: 'ESSAY', text: 'ما وظيفة حفظ الدين؟' },
      { id: 80, type: 'ESSAY', text: 'ما معنى حماية البيضة؟' },
      { id: 81, type: 'ESSAY', text: 'ما وظيفة إقامة الحدود؟' },
      { id: 82, type: 'ESSAY', text: 'ما المقصود بتقدير العطايا؟' },
      { id: 83, type: 'ESSAY', text: 'ما شروط القاضي؟' },
      { id: 84, type: 'ESSAY', text: 'ما أصول الأحكام؟' },
      { id: 85, type: 'ESSAY', text: 'من هو ناظر المظالم؟' },
      { id: 86, type: 'ESSAY', text: 'ما صفاته المطلوبة؟' },
      { id: 87, type: 'ESSAY', text: 'ما أهم أعمال ولاية المظالم؟' },
      { id: 88, type: 'ESSAY', text: 'ما هي غصوب السلطانية؟' },
      { id: 89, type: 'ESSAY', text: 'ما وزارة التفويض؟' },
      { id: 90, type: 'ESSAY', text: 'ما وزارة التنفيذ؟' },
    ]
  },
  {
    id: 'renaissance',
    title: 'اختبار عصر النهضة',
    description: 'اختبار حول عصر النهضة الأوروبية، وشخصياتها مثل ميكيافيلي وهوبز، والتحولات الفكرية والسياسية.',
    icon: 'pen',
    mcqQuestions: [
      { id: 1, type: 'MCQ', text: 'بدأ عصر النهضة في:', options: ['فرنسا', 'إيطاليا', 'إسبانيا', 'اليونان'], correctAnswerIndex: 1 },
      { id: 2, type: 'MCQ', text: 'هدف عصر النهضة كان:', options: ['نشر الاستعمار', 'إحياء قيم اليونان وروما', 'محاربة العلم', 'دعم الإقطاع'], correctAnswerIndex: 1 },
      { id: 3, type: 'MCQ', text: 'من أبرز فناني عصر النهضة:', options: ['فرجيل', 'البخاري', 'ليوناردو دافنشي', 'ابن رشد'], correctAnswerIndex: 2 },
      { id: 4, type: 'MCQ', text: 'من علماء عصر النهضة:', options: ['كوبرنيكوس وغاليليو', 'ابن الهيثم', 'نيوتن فقط', 'داروين'], correctAnswerIndex: 0 },
      { id: 5, type: 'MCQ', text: 'من خصائص فلسفة عصر النهضة:', options: ['الاعتماد على الكنيسة', 'الواقعية والعلمانية', 'العودة إلى الإقطاع', 'رفض العقل'], correctAnswerIndex: 1 },
      { id: 6, type: 'MCQ', text: 'نيكولا ميكيافيلي وُلِد في:', options: ['نابولي', 'فلورنسا', 'روما', 'ميلانو'], correctAnswerIndex: 1 },
      { id: 7, type: 'MCQ', text: 'يعد ميكيافيلي من رواد:', options: ['المثالية السياسية', 'الواقعية السياسية', 'الأخلاق الدينية', 'الفكر الاشتراكي'], correctAnswerIndex: 1 },
      { id: 8, type: 'MCQ', text: 'من مبادئ الفكر الميكيافيلي:', options: ['الأخلاق المطلقة', 'الغاية تبرر الوسيلة', 'رفض القوة', 'عدم استخدام العنف'], correctAnswerIndex: 1 },
      { id: 9, type: 'MCQ', text: 'يرى ميكيافيلي أن الأمير يقاتل:', options: ['بالقانون فقط', 'بالقوة فقط', 'بطريقتي الإنسان والحيوان', 'بالهرب'], correctAnswerIndex: 2 },
      { id: 10, type: 'MCQ', text: 'إن تعذر الجمع بين الهيبة والمحبة، يفضّل ميكيافيلي:', options: ['المحبة', 'الهيبة والخوف', 'الضعف', 'العطاء'], correctAnswerIndex: 1 },
      { id: 11, type: 'MCQ', text: 'التظاهر بالصفات الحسنة عند ميكيافيلي يعني:', options: ['امتلاكها فعلاً', 'عدم الحاجة إليها', 'الظهور بها دون الالتزام الدائم', 'رفضها تماماً'], correctAnswerIndex: 2 },
      { id: 12, type: 'MCQ', text: 'يرى أن الأنظمة الوراثية:', options: ['الأكثر فوضى', 'أكثر استقراراً', 'تحتاج ثورات', 'ضعيفة دائماً'], correctAnswerIndex: 1 },
      { id: 13, type: 'MCQ', text: 'يعتبر المرتزقة عند ميكيافيلي:', options: ['مفيدين', 'شجعاناً في الحرب', 'خطيرين وعديمي الفائدة', 'أوفياء للناس'], correctAnswerIndex: 2 },
      { id: 14, type: 'MCQ', text: 'ينصح ميكيافيلي بإلهاء الشعب عبر:', options: ['الضرائب', 'المهرجانات والاحتفالات', 'العزلة', 'الحروب'], correctAnswerIndex: 1 },
      { id: 15, type: 'MCQ', text: 'من هو توماس هوبز؟', options: ['فيلسوف يوناني', 'عالم اجتماع', 'فيلسوف سياسي إنجليزي', 'شاعر إيطالي'], correctAnswerIndex: 2 },
      { id: 16, type: 'MCQ', text: 'أشهر كتاب لهوبز هو:', options: ['الأمير', 'اللوياثان', 'الجمهورية', 'العقد الاجتماعي لروسو'], correctAnswerIndex: 1 },
      { id: 17, type: 'MCQ', text: 'اللوياثان يرمز إلى:', options: ['السالم', 'القوة الإلهية', 'الوحش الأسطوري رمز الدولة', 'الفلسفة اليونانية'], correctAnswerIndex: 2 },
      { id: 18, type: 'MCQ', text: 'يرى هوبز أن حالة الطبيعة هي:', options: ['هدوء واستقرار', 'حرب الكل ضد الكل', 'تعاون', 'رخاء'], correctAnswerIndex: 1 },
      { id: 19, type: 'MCQ', text: 'البشر في نظر هوبز:', options: ['خيرون بطبيعتهم', 'يسعون لصالح الآخرين', 'أنانيون يسعون لمصلحتهم', 'بلا رغبات'], correctAnswerIndex: 2 },
      { id: 20, type: 'MCQ', text: 'التنافس على السلطة عند هوبز يخلق:', options: ['الاستقرار', 'الخوف والريبة', 'الثقة', 'التفاهم'], correctAnswerIndex: 1 },
      { id: 21, type: 'MCQ', text: 'العقد الاجتماعي عند هوبز هو:', options: ['إجباري', 'طوعي', 'مؤقت', 'خاص بالنبلاء'], correctAnswerIndex: 1 },
      { id: 22, type: 'MCQ', text: 'بموجب العقد يتنازل الناس عن:', options: ['جزء من حقوقهم', 'حقوقهم الطبيعية بالكامل', 'حقوق الملك', 'المال'], correctAnswerIndex: 1 },
      { id: 23, type: 'MCQ', text: 'الطرف الذي لا يدخل في العقد هو:', options: ['الشعب', 'الملك', 'النبلاء', 'رجال الدين'], correctAnswerIndex: 1 },
      { id: 24, type: 'MCQ', text: 'يرى هوبز أن الشعب لا يحق له:', options: ['الدفاع عن نفسه', 'العمل', 'التمرد على الحاكم', 'طلب الأمن'], correctAnswerIndex: 2 },
      { id: 25, type: 'MCQ', text: 'أهم وظيفة للملك وفق العقد هي:', options: ['نشر الفلسفة', 'توفير الأمن', 'زيادة الضرائب', 'إلغاء الجيش'], correctAnswerIndex: 1 },
      { id: 26, type: 'MCQ', text: 'العبارة "العقود بلا سيف مجرد كلمات بلا قوة" تعني:', options: ['الحق للضعيف', 'ضرورة القوة لتنفيذ القانون', 'رفض القانون', 'رفض الدولة'], correctAnswerIndex: 1 },
      { id: 27, type: 'MCQ', text: 'يرى هوبز أن الحياة في الطبيعة:', options: ['سعيدة', 'سهلة', 'منعزلة وقاسية', 'فاضلة'], correctAnswerIndex: 2 },
      { id: 28, type: 'MCQ', text: 'يقول هوبز: "وُلدت أنا والخوف كتوأم" دلالة على:', options: ['الشجاعة', 'الطبيعة البشرية المليئة بالخوف', 'الحكمة', 'التفاؤل'], correctAnswerIndex: 1 },
      { id: 29, type: 'MCQ', text: 'يرى هوبز أن "القوة والخداع":', options: ['فساد', 'فضيلتان أساسيتان في الحرب', 'صفات مذمومة دائماً', 'لا علاقة لهما بالحرب'], correctAnswerIndex: 1 },
      { id: 30, type: 'MCQ', text: 'يرى أن التنازل عن الحقوق يقود إلى:', options: ['دولة ضعيفة', 'دولة مستقرة', 'صراع دائم', 'حرب أهلية'], correctAnswerIndex: 1 },
    ],
    tfQuestions: [
      { id: 31, type: 'TF', text: 'بدأ عصر النهضة في إيطاليا.', correctAnswer: true },
      { id: 32, type: 'TF', text: 'اهتم عصر النهضة بإحياء الفكر الإسلامي.', correctAnswer: false },
      { id: 33, type: 'TF', text: 'ميكيافيلي من رواد الواقعية.', correctAnswer: true },
      { id: 34, type: 'TF', text: 'يرى ميكيافيلي أن الغاية لا تبرر الوسيلة.', correctAnswer: false },
      { id: 35, type: 'TF', text: 'الأمير يجب أن يظهر بصفات حسنة.', correctAnswer: true },
      { id: 36, type: 'TF', text: 'يفضّل ميكيافيلي المحبة على الهيبة دائماً.', correctAnswer: false },
      { id: 37, type: 'TF', text: 'الأنظمة الوراثية أكثر استقراراً.', correctAnswer: true },
      { id: 38, type: 'TF', text: 'المرتزقة قوة يعتمد عليها دائماً.', correctAnswer: false },
      { id: 39, type: 'TF', text: 'يرى ميكيافيلي ضرورة امتلاك الصفات الحسنة فعلاً.', correctAnswer: false },
      { id: 40, type: 'TF', text: 'هوبز صاحب كتاب اللوياثان.', correctAnswer: true },
      { id: 41, type: 'TF', text: 'يرى هوبز أن البشر خيرون بطبيعتهم.', correctAnswer: false },
      { id: 42, type: 'TF', text: 'حالة الطبيعة هي حرب الكل ضد الكل.', correctAnswer: true },
      { id: 43, type: 'TF', text: 'العقد الاجتماعي عند هوبز طوعي.', correctAnswer: true },
      { id: 44, type: 'TF', text: 'الملك طرف رئيسي في العقد.', correctAnswer: false },
      { id: 45, type: 'TF', text: 'التمرد على الحاكم جائز عند هوبز.', correctAnswer: false },
      { id: 46, type: 'TF', text: 'هوبز يرى أن القوة ضرورية لتنفيذ العقود.', correctAnswer: true },
      { id: 47, type: 'TF', text: 'يرى هوبز أن الحياة في الطبيعة قصيرة وقاسية.', correctAnswer: true },
      { id: 48, type: 'TF', text: 'يرى أن الخوف جزء من الطبيعة البشرية.', correctAnswer: true },
      { id: 49, type: 'TF', text: 'يقول هوبز إن الخداع ليس له دور في الحرب.', correctAnswer: false },
      { id: 50, type: 'TF', text: 'يرى أن كل فرد يسعى للوصول للسلطة.', correctAnswer: true },
      { id: 51, type: 'TF', text: 'التنافس يخلق الريبة والخوف.', correctAnswer: true },
      { id: 52, type: 'TF', text: 'يرى أن الناس متساوون في الطبيعة.', correctAnswer: true },
      { id: 53, type: 'TF', text: 'المساواة عنده تؤدي غالباً للنزاع.', correctAnswer: true },
      { id: 54, type: 'TF', text: 'العقد بين الناس أنفسهم.', correctAnswer: true },
      { id: 55, type: 'TF', text: 'الملك يقدم الحماية مقابل السلطة.', correctAnswer: true },
      { id: 56, type: 'TF', text: 'يتنازل الناس عن حقوقهم الطبيعية.', correctAnswer: true },
      { id: 57, type: 'TF', text: 'المرتزقة أكثر إخلاصاً من الجيوش الوطنية.', correctAnswer: false },
      { id: 58, type: 'TF', text: 'ميكيافيلي يفضل أن يكون الأمير محبوباً إن أمكن.', correctAnswer: true },
      { id: 59, type: 'TF', text: 'يرى أن الجيوش الوطنية أفضل للدولة.', correctAnswer: true },
      { id: 60, type: 'TF', text: 'هوبز يرى أن الفوضى أخف ضرراً من الاستبداد.', correctAnswer: false },
    ],
    essayQuestions: [
      { id: 61, type: 'ESSAY', text: 'ما خصائص عصر النهضة؟' },
      { id: 62, type: 'ESSAY', text: 'ما هدف النهضة؟' },
      { id: 63, type: 'ESSAY', text: 'من أبرز فناني النهضة؟' },
      { id: 64, type: 'ESSAY', text: 'من علماء النهضة؟' },
      { id: 65, type: 'ESSAY', text: 'ما التحول الفلسفي الذي حدث؟' },
      { id: 66, type: 'ESSAY', text: 'ما خصائص فلسفة عصر النهضة؟' },
      { id: 67, type: 'ESSAY', text: 'من هو ميكيافيلي؟' },
      { id: 68, type: 'ESSAY', text: 'ما أهم مبادئ الفكر الميكيافيلي؟' },
      { id: 69, type: 'ESSAY', text: 'اشرح "نظرية الأمير ذو الطبيعتين".' },
      { id: 70, type: 'ESSAY', text: 'ما موقفه من المحبة والهيبة؟' },
      { id: 71, type: 'ESSAY', text: 'ما معنى التظاهر بالصفات الحسنة؟' },
      { id: 72, type: 'ESSAY', text: 'لماذا الأنظمة الوراثية مستقرة؟' },
      { id: 73, type: 'ESSAY', text: 'لماذا المرتزقة خطرون؟' },
      { id: 74, type: 'ESSAY', text: 'ما دور الجيوش الوطنية؟' },
      { id: 75, type: 'ESSAY', text: 'ما معنى إلهاء الشعوب عند ميكيافيلي؟' },
      { id: 76, type: 'ESSAY', text: 'من هو توماس هوبز؟' },
      { id: 77, type: 'ESSAY', text: 'ما موضوع كتاب اللوياثان؟' },
      { id: 78, type: 'ESSAY', text: 'ما معنى حالة الطبيعة؟' },
      { id: 79, type: 'ESSAY', text: 'كيف يرى هوبز الإنسان؟' },
      { id: 80, type: 'ESSAY', text: 'ماذا ينتج عن التنافس على السلطة؟' },
      { id: 81, type: 'ESSAY', text: 'ما معنى العقد الاجتماعي؟' },
      { id: 82, type: 'ESSAY', text: 'لماذا يتنازل الناس عن حقوقهم؟' },
      { id: 83, type: 'ESSAY', text: 'لماذا لا يدخل الملك طرفاً في العقد؟' },
      { id: 84, type: 'ESSAY', text: 'لماذا لا يحق التمرد على الحاكم؟' },
      { id: 85, type: 'ESSAY', text: 'ماذا تعني عبارة "العقود بلا سيف مجرد كلمات بلا قوة"؟' },
      { id: 86, type: 'ESSAY', text: 'كيف تبدو الحياة في الطبيعة؟' },
      { id: 87, type: 'ESSAY', text: 'ماذا يقصد بقوله "وُلدت أنا والخوف كتوأم"؟' },
      { id: 88, type: 'ESSAY', text: 'ما مكانة الخداع والقوة في الحرب؟' },
      { id: 89, type: 'ESSAY', text: 'ما علاقة المساواة بالنزاع في الطبيعة؟' },
      { id: 90, type: 'ESSAY', text: 'ما أثر التنازل عن الحقوق على الدولة؟' },
    ]
  },
  {
    id: 'ibn-taymiyyah',
    title: 'اختبار ابن تيمية (السياسة الشرعية)',
    description: 'اختبار في الفكر السياسي لابن تيمية، مفهوم الإمارة، الأمانة والقوة، واختيار الولاة.',
    icon: 'book',
    mcqQuestions: [
      { id: 1, type: 'MCQ', text: 'وُلِد ابن تيمية في:', options: ['دمشق', 'القاهرة', 'حرّان', 'بغداد'], correctAnswerIndex: 2 },
      { id: 2, type: 'MCQ', text: 'سنة ولادة ابن تيمية هي:', options: ['600هـ', '661هـ', '700هـ', '728هـ'], correctAnswerIndex: 1 },
      { id: 3, type: 'MCQ', text: 'نزحت أسرته إلى الشام بسبب:', options: ['التجارة', 'الجفاف', 'هجمات التتار', 'التعليم'], correctAnswerIndex: 2 },
      { id: 4, type: 'MCQ', text: 'يُلقّب ابن تيمية بـ:', options: ['شيخ الفقهاء', 'شيخ الإسلام', 'إمام الأمة', 'المفسر الأكبر'], correctAnswerIndex: 1 },
      { id: 5, type: 'MCQ', text: 'تميز ابن تيمية بـ:', options: ['قلة مؤلفاته', 'العلم بالشريعة واللغة', 'الاقتصار على الفقه', 'ترك المناظرات'], correctAnswerIndex: 1 },
      { id: 6, type: 'MCQ', text: 'من الأسباب التي أدت إلى سجنه:', options: ['السفر', 'مواجهة التتار ونقاش خصومه', 'ترك التدريس', 'عدم التأليف'], correctAnswerIndex: 1 },
      { id: 7, type: 'MCQ', text: 'توفي ابن تيمية سنة:', options: ['700هـ', '728هـ', '750هـ', '770هـ'], correctAnswerIndex: 1 },
      { id: 8, type: 'MCQ', text: 'يرى ابن تيمية أن الحكم يجب أن يكون:', options: ['وفق الأعراف', 'وفق الشريعة', 'وفق العادات', 'وفق السياسة فقط'], correctAnswerIndex: 1 },
      { id: 9, type: 'MCQ', text: 'ضرورة وجود إمارة الإسلام عنده بسبب:', options: ['تحقيق الرفاه فقط', 'حفظ الأمن وتطبيق الشرع', 'زيادة الأموال', 'كثرة الجيوش'], correctAnswerIndex: 1 },
      { id: 10, type: 'MCQ', text: 'من الانتقادات الموجهة لفكر ابن تيمية:', options: ['قلة تلاميذه', 'استغلال المتطرفين لبعض آرائه', 'بعده عن السياسة', 'عدم الكتابة عن الحكم'], correctAnswerIndex: 1 },
      { id: 11, type: 'MCQ', text: 'واجب ولي الأمر عند ابن تيمية هو:', options: ['اختيار الأقرباء', 'اختيار الأصلح', 'اختيار الأغنى', 'اختيار الأقدم'], correctAnswerIndex: 1 },
      { id: 12, type: 'MCQ', text: 'من الفئات التي يجب اختيار الأكفأ منها:', options: ['الخطباء فقط', 'القضاة والأمراء', 'الطلاب', 'عامة الناس'], correctAnswerIndex: 1 },
      { id: 13, type: 'MCQ', text: 'أولو الأمر عند ابن تيمية هم:', options: ['التجار', 'الشعراء', 'الأمراء والعلماء', 'القراء'], correctAnswerIndex: 2 },
      { id: 14, type: 'MCQ', text: 'الإمارة ضرورة لأنها تحقق:', options: ['التفرد', 'الاجتماع والتعاون', 'زيادة الأموال', 'القوة العسكرية فقط'], correctAnswerIndex: 1 },
      { id: 15, type: 'MCQ', text: 'ترتكز الولاية على:', options: ['القوة والمال', 'الأمانة والقرابة', 'القوة والأمانة', 'العلم والشهرة'], correctAnswerIndex: 2 },
      { id: 16, type: 'MCQ', text: 'من القوة في إمارة الحرب:', options: ['العدل', 'شجاعة القلب', 'الصمت', 'الزهد'], correctAnswerIndex: 1 },
      { id: 17, type: 'MCQ', text: 'القوة في الحكم بين الناس تعتمد على:', options: ['الطاعة', 'العلم بالعدل', 'الثراء', 'كثرة الأتباع'], correctAnswerIndex: 1 },
      { id: 18, type: 'MCQ', text: 'الأمانة تشمل:', options: ['خشية الله', 'حب الرياسة', 'اتباع الأهواء', 'طلب المناصب'], correctAnswerIndex: 0 },
      { id: 19, type: 'MCQ', text: 'يرى ابن تيمية أن اجتماع القوة والأمانة في شخص واحد:', options: ['كثير', 'نادر', 'مستحيل', 'غير مهم'], correctAnswerIndex: 1 },
      { id: 20, type: 'MCQ', text: 'في إمارة الحروب يُقَدَّم:', options: ['الأمين الضعيف', 'القوي الشجاع', 'قليل الخبرة', 'غير المؤهل'], correctAnswerIndex: 1 },
      { id: 21, type: 'MCQ', text: 'البشر الذين يطلبون العلو والفساد وصفهم بـ:', options: ['أهل العلم', 'الملوك الجائرين', 'الأخيار', 'أهل الجنة'], correctAnswerIndex: 1 },
      { id: 22, type: 'MCQ', text: 'من يفسدون دون طلب العلو هم:', options: ['العلماء', 'المتدينون', 'المجرمون والسراق', 'القادة'], correctAnswerIndex: 2 },
      { id: 23, type: 'MCQ', text: 'من يريد العلو دون فساد هم:', options: ['أهل الجنة', 'العلماء والمتدينون', 'الفاسدون', 'السراق'], correctAnswerIndex: 1 },
      { id: 24, type: 'MCQ', text: 'من لا يريدون علواً ولا فساداً وصفهم بـ:', options: ['الفقهاء', 'أهل الجنة', 'الجنود', 'الأمراء'], correctAnswerIndex: 1 },
      { id: 25, type: 'MCQ', text: 'يرى ابن تيمية أن طلب المناصب هو:', options: ['دليل قوة', 'سبب للمنع', 'ميزة', 'ضرورة'], correctAnswerIndex: 1 },
      { id: 26, type: 'MCQ', text: 'شبّه الحرص على المال والرياسة بـ:', options: ['الربيع', 'الذئبين الجائعين', 'المطر', 'الشجرة المثمرة'], correctAnswerIndex: 1 },
      { id: 27, type: 'MCQ', text: 'العاملون على الخراج والصدقات عنده يجب أن يكونوا:', options: ['الأقوى', 'الأغنى', 'الأصلح والأكفأ', 'الأقدم'], correctAnswerIndex: 2 },
      { id: 28, type: 'MCQ', text: 'نظرية التوازن في السلطة تقوم على:', options: ['تقديم الأقل نفعاً', 'تقديم الأنفع للولاية', 'تقديم الأقرباء', 'تقديم الأكثر مالاً'], correctAnswerIndex: 1 },
      { id: 29, type: 'MCQ', text: 'إذا احتاجت الولاية إلى الأمانة أكثر، فإنه يُقَدَّم:', options: ['القوي', 'الأمين', 'الأغنى', 'الأسرع'], correctAnswerIndex: 1 },
      { id: 30, type: 'MCQ', text: 'يرى ابن تيمية أن مصالح البشر لا تستقيم إلا بـ:', options: ['الفرقة', 'العزلة', 'الاجتماع والتعاون', 'الصراع'], correctAnswerIndex: 2 },
    ],
    tfQuestions: [
      { id: 31, type: 'TF', text: 'ابن تيمية وُلِد في حرّان.', correctAnswer: true },
      { id: 32, type: 'TF', text: 'نزحت أسرته إلى الشام بسبب التجارة.', correctAnswer: false },
      { id: 33, type: 'TF', text: 'لقب ابن تيمية هو شيخ الإسلام.', correctAnswer: true },
      { id: 34, type: 'TF', text: 'واجه التتار بالسلاح.', correctAnswer: true },
      { id: 35, type: 'TF', text: 'توفي سنة 728هـ.', correctAnswer: true },
      { id: 36, type: 'TF', text: 'يرى أن الحكم يجب أن يكون وفق الشريعة.', correctAnswer: true },
      { id: 37, type: 'TF', text: 'أكد على ضرورة وجود إمارة للإسلام.', correctAnswer: true },
      { id: 38, type: 'TF', text: 'لم يتعرض فكره لأي انتقادات.', correctAnswer: false },
      { id: 39, type: 'TF', text: 'يرى أن ولي الأمر يجب أن يختار الأصلح.', correctAnswer: true },
      { id: 40, type: 'TF', text: 'أولو الأمر عنده هم الأمراء والعلماء.', correctAnswer: true },
      { id: 41, type: 'TF', text: 'الإمارة عنده ليست ضرورة.', correctAnswer: false },
      { id: 42, type: 'TF', text: 'تقوم الولاية على القوة والأمانة.', correctAnswer: true },
      { id: 43, type: 'TF', text: 'القوة تشمل شجاعة القلب والخبرة بالحروب.', correctAnswer: true },
      { id: 44, type: 'TF', text: 'الأمانة تشمل خشية الله.', correctAnswer: true },
      { id: 45, type: 'TF', text: 'اجتماع القوة والأمانة كثير الحدوث.', correctAnswer: false },
      { id: 46, type: 'TF', text: 'في إمارة الحرب يُقَدَّم القوي الشجاع.', correctAnswer: true },
      { id: 47, type: 'TF', text: 'من البشر من يفسدون دون طلب العلو.', correctAnswer: true },
      { id: 48, type: 'TF', text: 'أهل الجنة عنده لا يريدون علواً ولا فساداً.', correctAnswer: true },
      { id: 49, type: 'TF', text: 'طلب المناصب سبب للمنع.', correctAnswer: true },
      { id: 50, type: 'TF', text: 'شبّه الحرص على الرياسة بذئبين جائعين.', correctAnswer: true },
      { id: 51, type: 'TF', text: 'القوة في الحكم تحتاج العلم بالعدل.', correctAnswer: true },
      { id: 52, type: 'TF', text: 'يرى أن السلطة تحتاج توازناً.', correctAnswer: true },
      { id: 53, type: 'TF', text: 'الحرص على المال يفسد الدين.', correctAnswer: true },
      { id: 54, type: 'TF', text: 'العلماء والمتدينون يطلبون العلو دون فساد.', correctAnswer: true },
      { id: 55, type: 'TF', text: 'المجرمون يطلبون العلو والفساد.', correctAnswer: false },
      { id: 56, type: 'TF', text: 'من لا يطلبون علواً ولا فساداً هم أهل النار.', correctAnswer: false },
      { id: 57, type: 'TF', text: 'الانتقادات على ابن تيمية سببها سوء فهم بعض الجماعات.', correctAnswer: true },
      { id: 58, type: 'TF', text: 'يجب على ولي الأمر اختيار الأكفأ في الولاية.', correctAnswer: true },
      { id: 59, type: 'TF', text: 'يرى ابن تيمية أن الإنسان وحده يستطيع تحقيق حاجاته.', correctAnswer: false },
      { id: 60, type: 'TF', text: 'القوة في الحكم تشمل القدرة على تنفيذ الأحكام.', correctAnswer: true },
    ],
    essayQuestions: [
      { id: 61, type: 'ESSAY', text: 'من هو ابن تيمية؟' },
      { id: 62, type: 'ESSAY', text: 'لماذا نزحت أسرته إلى الشام؟' },
      { id: 63, type: 'ESSAY', text: 'ما سبب شهرته؟' },
      { id: 64, type: 'ESSAY', text: 'ما أبرز ملامح شخصيته العلمية؟' },
      { id: 65, type: 'ESSAY', text: 'لماذا سُجن عدة مرات؟' },
      { id: 66, type: 'ESSAY', text: 'ما معنى الحكم للإسلام عنده؟' },
      { id: 67, type: 'ESSAY', text: 'ما أهمية إمارة الإسلام؟' },
      { id: 68, type: 'ESSAY', text: 'ما سبب الانتقادات التي تعرض لها فكره؟' },
      { id: 69, type: 'ESSAY', text: 'ما واجب ولي الأمر في اختيار الولاة؟' },
      { id: 70, type: 'ESSAY', text: 'من هم أولو الأمر؟' },
      { id: 71, type: 'ESSAY', text: 'لماذا الإمارة ضرورة؟' },
      { id: 72, type: 'ESSAY', text: 'ما أركان الولاية؟' },
      { id: 73, type: 'ESSAY', text: 'ما القوة في إمارة الحرب؟' },
      { id: 74, type: 'ESSAY', text: 'ما القوة في الحكم؟' },
      { id: 75, type: 'ESSAY', text: 'ما معنى الأمانة عنده؟' },
      { id: 76, type: 'ESSAY', text: 'لماذا نادر اجتماع القوة والأمانة؟' },
      { id: 77, type: 'ESSAY', text: 'ما معيار تقديم الولاة عنده؟' },
      { id: 78, type: 'ESSAY', text: 'كيف يتعامل مع حالة تفوق القوي على الأمين؟' },
      { id: 79, type: 'ESSAY', text: 'كيف يتعامل مع حالة تفوق الأمين على القوي؟' },
      { id: 80, type: 'ESSAY', text: 'اذكر الصنف الأول من البشر عنده.' },
      { id: 81, type: 'ESSAY', text: 'الصنف الثاني من البشر؟' },
      { id: 82, type: 'ESSAY', text: 'الصنف الثالث؟' },
      { id: 83, type: 'ESSAY', text: 'الصنف الرابع؟' },
      { id: 84, type: 'ESSAY', text: 'لماذا يمنع المناصب عمن يطلبها؟' },
      { id: 85, type: 'ESSAY', text: 'ما أثر الحرص على الرياسة؟' },
      { id: 86, type: 'ESSAY', text: 'ما تشبيه ابن تيمية للحرص على المال والرياسة؟' },
      { id: 87, type: 'ESSAY', text: 'ما صفات موظفي الأموال عنده؟' },
      { id: 88, type: 'ESSAY', text: 'ما علاقة الإمارة بتحقيق مصالح البشر؟' },
      { id: 89, type: 'ESSAY', text: 'كيف تُختار الولاية بناءً على طبيعتها؟' },
      { id: 90, type: 'ESSAY', text: 'ما سبب تقديم الأنفع في نظرية التوازن؟' },
    ]
  }
];